version: "3"
services:
  postgresdb:
    image: akeron1:1.0.0
    restart: unless-stopped
    ports:
      - 4000
    environment:
      TOKEN_SECRET_KEY: task_management_db_secret_key
      DATABASE_URL: postgresql://akeron:Pcvinpostgres@postgresakeron.cbjrqddvgoeg.eu-central-1.rds.amazonaws.com:5432/akerondatabase
      PORT: 4000
