version: "3"
services:
  postgresdb:
    image: 863872515231.dkr.ecr.eu-central-1.amazonaws.com/akeronecr:1.0.0
    restart: unless-stopped
    ports:
      - 4000:5432
    environment:
      POSTGRES_USER: akeron
      POSTGRES_PASSWORD: Pcvinpostgres
      POSTGRES_DB: akerondatabase
